# Generated by Django 6.0.2 on 2026-02-14 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='focus_body_parts',
            field=models.ManyToManyField(blank=True, related_name='focused_workouts', to='workout.bodypart'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 14, 18, 21, 1, 52775)),
        ),
    ]
